{
 "title": "WIP",
 "time": { "from": "now-15s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Processes online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "Time since last activity",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "import \"join\"\nimport \"system\"\nimport \"array\"\nimport \"internal/debug\"\n\nheartbeats = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r[\"_measurement\"] == \"FederateNames\" and r[\"_field\"] == \"other_process_name\"))\n  |> rename(columns: {\"_value\": \"other_process_name\"})\n  |> group()\n  |> keep(columns: [\"other_process_name\", \"_time\", \"process_name\"])\ntracepoints = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r[\"_measurement\"] == \"TraceRecord\" and r[\"_field\"] == \"process_id\"))\n  |> rename(columns: {\"_value\": \"process_id\"})\n  |> keep(columns: [\"process_id\", \"_time\", \"process_name\"])\n\nlatest_tracepoints = tracepoints |> group(columns: [\"process_id\"]) |> max(column: \"_time\") |> group()\n\nisEmpty = (tables) => {\n\tcolumnsArray = tables\n\t\t|> columns()\n\t\t|> findColumn(fn: (key) => true, column: \"_value\")\n\treturn length(arr: columnsArray) == 0\n}\n\nd = join.left(\n  left: heartbeats |> keep(columns: [\"other_process_name\"]),\n  right: if isEmpty(tables: latest_tracepoints)\n    then array.from(rows: [{\n      process_id: debug.null(type: \"int\"),\n      _time: time(v: 0),\n      process_name: debug.null(type: \"string\")}])\n    else latest_tracepoints,\n  on: (l, r) => l.other_process_name == r.process_name,\n  as: (l, r) => ({l with\n    other_time: r._time\n  }))\ne = join.left(\n  left: d, right: heartbeats,\n  on: (l, r) => l.other_process_name == r.process_name,\n  as: (l, r) => (if not exists l.other_time or r._time > l.other_time\n    then (if not exists r._time then {l with greater_time: time(v: 0), last_message: \"NONE\"} else {l with greater_time: r._time, last_message: \"HEARTBEAT\"})\n    else {l with greater_time: l.other_time, last_message: \"TRACEPOINT\"})\n  )\n  |> keep(columns: [\"greater_time\", \"other_process_name\", \"last_message\"])\n  |> group(columns: [\"other_process_name\"])\n  |> max(column: \"greater_time\")\n  |> group()\n  |> map(fn: (r) => ({r with time_since_last_activity:\n    if r.greater_time == time(v: 0)\n     then debug.null(type: \"time\")\n     else (int(v: system.time()) - int(v: r.greater_time)) / 1000000}))\n\nret = e\n  |> drop(columns: [\"greater_time\"])\n  |> map(fn: (r) => ({r with status: if not exists r.time_since_last_activity\n    then \"DISCONNECTED\"\n    else (if r.last_message == \"TRACEPOINT\" then \"OK\" else \"QUIET\")}))\n  |> drop(columns: [\"last_message\"])\n  |> rename(columns: {\n    \"other_process_name\": \"Process\",\n    \"time_since_last_activity\": \"Age of latest data (ms)\"\n    })\n\nret"
    }
   ]
  },
  {
   "title": "Invocations by reactor",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r[\"_field\"] == \"process_id\")\n  |> filter(fn: (r) => r[\"event_kind_description\"] == \"Reaction starts\")\n  |> group()\n  |> drop(columns: [\"host\", \"worker\", \"dst_id\", \"src_id\", \"_field\", \"_time\", \"process_name\", \"_measurement\"])\n  |> group(columns: [\"id_description\"])\n  |> count()\n  |> group()\n  |> rename(columns: {id_description: \"Reactor\", _value: \"Number of reaction executions\"})"
    }
   ]
  },
  {
   "title": "Processes disconnected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "Lag (nanoseconds)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lag\")\n  |> drop(columns: [\"host\"])"
    }
   ]
  },
  {
   "title": "Logical time by process",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "times = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r[\"_field\"] == \"logical_time\"\n    and r.event_kind_description == \"Scheduler advancing time ends\")\n  |> keep(columns: [\"_time\", \"_value\", \"event_kind_description\", \"process_name\"])\n  |> group(columns: [\"process_name\"])\n  |> sort(columns: [\"_time\"])\n  |> map(fn: (r) => ({r with ns: uint(v: r._time)}))\n  |> difference(columns: [\"ns\"])\n  |> map(fn: (r) => ({r with \"End time\": time(v: uint(v: int(v: r._time) + int(v: r.ns)))}))\n  |> rename(columns: {\"_time\": \"Start time\"})\n  |> map(fn: (r) => ({r with \"event\": r._value}))\n\nret = times\n  |> group()\n  |> pivot(\n    rowKey: [\"End time\", \"Start time\"],\n    columnKey: [\"process_name\"],\n    valueColumn: \"event\"\n  )\n\nret"
    }
   ]
  },
  {
   "title": "Reactions by reactor",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "reactions = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lag\"\n    and (r.event_kind_description == \"Reaction starts\" or r.event_kind_description == \"Reaction ends\"))\n  |> keep(columns: [\"_time\", \"_value\", \"event_kind_description\", \"id_description\"])\n  |> group(columns: [\"id_description\"])\n  |> sort(columns: [\"_time\"])\n  |> map(fn: (r) => ({r with ns: uint(v: r._time)}))\n  |> difference(columns: [\"ns\"])\n  |> filter(fn: (r) => r.event_kind_description == \"Reaction ends\")\n  |> map(fn: (r) => ({r with \"Start time\": time(v: uint(v: int(v: r._time) - int(v: r.ns)))}))\n  |> rename(columns: {\"_time\": \"End time\"})\n  |> map(fn: (r) => ({r with \"event\": r._value}))\n\nret = reactions\n  |> group()\n  |> pivot(\n    rowKey: [\"End time\", \"Start time\"],\n    columnKey: [\"id_description\"],\n    valueColumn: \"event\"\n  )\n\nret"
    }
   ]
  },
  {
   "title": "Max lag (nanoseconds) in the current time interval",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TraceRecord\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lag\")\n  |> keep(columns: [\"process_name\", \"_value\"])\n  |> rename(columns: {_value: \"lag in \"})"
    }
   ]
  }
 ]
}